const BOSS_CONTENT = {
  funnyTexts: {
    novice: [
      "Every boss starts somewhere",
      "Still reading the boss manual",
      "Coffee break boss energy",
      "Boss in training mode",
      "Keyboard louder than confidence",
      "Assistant to the regional boss",
      "Wi-Fi stronger than power",
      "Still unlocking boss skills",
      "Boss vibes buffering...",
      "Learning the secret handshake",
      "Boss shoes still shiny",
      "Power nap certified",
      "Boss alarm snoozed",
      "Spreadsheet warrior",
      "Boss aura loading...",
      "Motivation pending approval",
      "Office chair CEO",
      "Almost intimidating",
      "Boss energy on airplane mode",
      "Practicing the stare",
      "Budget boss",
      "Boss level: tutorial",
      "Confidence warming up",
      "Boss instincts downloading...",
      "Legend pending",
      "Small boss, big dreams",
      "Not bossy-just ambitious",
      "CEO of \"maybe later\"",
      "Junior boss vibes. You'll get there",
      "Still in tutorial mode",
      "Small steps. Big boss later",
      "Boss energy loading... please wait",
      "Accidentally powerful",
      "Still reading the tutorial",
      "Boss in training wheels",
      "Confidently unsure",
      "Main character in the background",
      "Pressed the boss button by mistake",
      "Boss trial version",
      "Still assembling authority",
      "Mic muted, energy muted",
      "Trying to look busy",
      "Boss not installed",
      "Learning how to nod seriously",
      "Practice boss detected",
      "Boss preview mode",
      "Still figuring out the suit",
      "Confidence under construction",
      "Almost took charge",
      "Boss aura flickering",
      "Still syncing ambition",
      "Boss-lite version",
      "Downloading confidence patch",
      "Trying to look important",
      "Boss energy on low battery",
      "Soft launch boss",
      "Minor boss encounter",
      "Still unlocking presence",
      "Confidence needs restart",
      "Boss energy pending update",
      "Your tie is doing most of the work",
      "Boss energy rented by the hour",
      "Leadership stuck in traffic",
      "Boss mode after one snack",
      "Your stare almost scared the printer",
      "Your badge says intern in bold",
      "Power suit sold separately",
      "You almost looked in charge there",
      "Boss energy, hold the boss",
      "You brought vibes, not authority",
      "Your stapler outranks you today",
      "That was a very brave shrug",
      "Your coffee is leading this team",
      "You supervise exactly one snack",
      "Your aura forgot its password",
      "You issued one very soft command",
      "Authority pending manager approval",
      "You look promoted in low light",
      "Your confidence needs charging",
      "You almost inspired the stapler",
      "You brought intern meeting energy",
      "Your chair has stronger presence",
      "A future boss is buffering",
      "You nearly scared a paperclip",
      "That was almost executive behavior",
      "The office plant believes in you",
      "You have manager-adjacent vibes"
    ],
    apprentice: [
      "Boss with potential",
      "Confidence upgraded",
      "People starting to notice",
      "Boss energy rising",
      "Office legend rumors",
      "Still humble, mostly",
      "Boss handshake unlocked",
      "Voice carries further",
      "Meetings fear you",
      "Keyboard respected",
      "Coffee obeys you",
      "Promotion aura detected",
      "Boss mode warming",
      "Authority increasing",
      "Decisions slightly faster",
      "Boss instincts sharpening",
      "Desk presence strong",
      "Leadership beta",
      "Power stance improving",
      "Boss shoes broken in",
      "Respect installing...",
      "Boss playlist curated",
      "Confidence compiling...",
      "Boss brain online",
      "Almost legendary",
      "You're not late-you're dramatic",
      "Rising like fresh toast",
      "CEO of \"good enough\"",
      "Respectable boss energy",
      "You're leveling up fast",
      "Not bad... not bad at all",
      "Boss energy stabilizing",
      "Authority gaining traction",
      "Boss instincts kicking in",
      "Less guessing, more deciding",
      "Boss presence loading fast",
      "You might be in charge soon",
      "Eyes starting to follow",
      "Boss mode unlocked (partial)",
      "You mean business sometimes",
      "Leadership forming nicely",
      "Respect increasing steadily",
      "Almost running things",
      "You're no longer background noise",
      "Your inbox fears your confidence",
      "You now nod like you own a printer",
      "Your mug has manager energy",
      "You point at charts with authority",
      "Your nod just approved a budget",
      "People wait for your fake wisdom",
      "You now walk with agenda energy",
      "Your calendar is mildly afraid",
      "The break room knows your name",
      "You now look busy on purpose",
      "Your keyboard sounds expensive",
      "People trust your confident guessing",
      "Your shoes now sound promoted",
      "You bring light supervisor chaos",
      "Your clipboard now means business",
      "Your emails now arrive with weight",
      "You now pause for dramatic effect",
      "Your handshake has follow-up energy",
      "Even your typos sound deliberate",
      "You now inspire careful nodding",
      "Your confidence has a budget line",
      "You bring almost-boss energy",
      "Your coffee order sounds managerial",
      "You now interrupt with useful vibes",
      "The copier respects your hustle",
      "You have become mildly intimidating"
    ],
    rising: [
      "People listen now",
      "Boss energy undeniable",
      "Meetings end faster",
      "Decisions land hard",
      "Boss presence felt",
      "Power suit energy",
      "Confidence at scale",
      "Voice carries weight",
      "Room temperature changes",
      "Boss aura stable",
      "Respect delivered",
      "Authority unlocked",
      "Boss instincts sharp",
      "Momentum building",
      "Eyes follow you",
      "Keyboard obeys",
      "Boss energy certified",
      "Leadership activated",
      "No nonsense detected",
      "Commanding presence",
      "Boss level rising",
      "Strategy installed",
      "Confidence overflow",
      "Boss energy flex",
      "Legend forming",
      "You negotiate with gravity",
      "Meetings request you",
      "Boss momentum is real",
      "People are starting to listen",
      "Confidence unlocked",
      "The office plant is loyal to you",
      "People pause when your chair spins",
      "Your coffee order sounds strategic",
      "Your glance has manager settings",
      "Your silence does the talking",
      "You radiate polished urgency",
      "Your chair turn means business",
      "You could motivate a stapler",
      "People nod before you finish",
      "You now manage room temperature",
      "Your entrance gets its own memo",
      "Your eyebrows now set direction",
      "You now look expensive to HR",
      "Your pauses have executive timing",
      "You now boss with premium pixels"
    ],
    elite: [
      "Room goes quiet",
      "Boss energy intimidating",
      "Decisions shape reality",
      "Authority unquestioned",
      "Power walks louder",
      "Boss aura maxed",
      "Respect guaranteed",
      "Leadership absolute",
      "Meetings obey",
      "Confidence unstoppable",
      "Boss instincts elite",
      "Commanding silence",
      "Strategy flawless",
      "Boss presence heavy",
      "Influence detected",
      "Boss energy peaks",
      "Power undeniable",
      "Leadership refined",
      "Elite mindset active",
      "Boss moves decisive",
      "Authority mastered",
      "Confidence lethal",
      "Boss legend near",
      "Feared politely",
      "Your calendar fears you",
      "Handshake is a contract",
      "Elite aura detected",
      "CEO energy. No refunds",
      "Boss energy perfected",
      "Authority radiates outward",
      "Leadership looks easy",
      "Your footsteps sound expensive",
      "The room straightens up for you",
      "Your glance just promoted somebody",
      "Your posture closed three deals",
      "You have luxury spreadsheet energy",
      "Your wristwatch sets team culture",
      "You radiate paid parking energy",
      "You approve things by standing near",
      "Your coffee arrives with security",
      "Your calendar wears a tuxedo",
      "You look like premium expenses"
    ],
    legendary: [
      "Boss mythology confirmed",
      "Legend walks among us",
      "Reality bends slightly",
      "Boss energy absolute",
      "Power unmatched",
      "History remembers this",
      "Authority unquestionable",
      "Boss aura eternal",
      "Legends whisper",
      "Respect infinite",
      "Power level capped",
      "Boss final form",
      "Legacy activated",
      "Influence timeless",
      "Boss energy god-tier",
      "Legend certified",
      "Myth unlocked",
      "Boss presence iconic",
      "Power perfected",
      "History rewritten",
      "Boss energy complete",
      "Ultimate authority",
      "Legend status permanent",
      "Reality approves",
      "Boss achieved",
      "Your name is a strategy",
      "Even luck takes notes",
      "The room pays rent to you",
      "Legend status confirmed",
      "Absolute unit of boss",
      "This is what power looks like",
      "You did not roll this, you earned it",
      "Other bosses listen",
      "Power level confidential",
      "Destiny adjusted accordingly",
      "Achieved boss enlightenment",
      "Boss of bosses",
      "Reality complies",
      "Influence without limit",
      "Authority transcends context",
      "Outcomes align instantly",
      "Your Wi-Fi connects out of respect",
      "Your ringtone sounds historic",
      "Even luck arrives five minutes early",
      "Your coffee break moved the market",
      "The skyline mirrors your mood"
    ]
  },
  successQuotes: [
    "Aristotle: We are what we repeatedly do. Excellence, then, is a habit.",
    "Aristotle: Quality is not an act, it is a habit.",
    "Plato: The beginning is the most important part of the work.",
    "Epictetus: First say to yourself what you would be.",
    "Epictetus: No great thing is created suddenly.",
    "Seneca: Luck is what happens when preparation meets opportunity.",
    "Seneca: The best preparation for tomorrow is doing your best today.",
    "Marcus Aurelius: What stands in the way becomes the way.",
    "Confucius: It does not matter how slowly you go as long as you do not stop.",
    "Confucius: Our greatest glory is not in never falling, but in rising every time we fall.",
    "Confucius: The man who moves a mountain begins by carrying away small stones.",
    "Sun Tzu: Opportunities multiply as they are seized.",
    "Sun Tzu: Victorious warriors win first and then go to war.",
    "Sun Tzu: In the midst of chaos, there is also opportunity.",
    "Lao Tzu: A journey of a thousand miles begins with a single step.",
    "Leonardo da Vinci: Simplicity is the ultimate sophistication.",
    "Leonardo da Vinci: Learning never exhausts the mind.",
    "Benjamin Franklin: Well done is better than well said.",
    "Benjamin Franklin: Energy and persistence conquer all things.",
    "Thomas Jefferson: I find that the harder I work, the more luck I seem to have.",
    "Thomas Jefferson: Do you want to know who you are? Don't ask. Act.",
    "Abraham Lincoln: Whatever you are, be a good one.",
    "Theodore Roosevelt: Believe you can and you're halfway there.",
    "Theodore Roosevelt: Do what you can, with what you have, where you are.",
    "Theodore Roosevelt: Far better it is to dare mighty things.",
    "Andrew Carnegie: No man will make a great leader who wants to do it all himself.",
    "Andrew Carnegie: Concentrate your energies on one definite chief aim.",
    "Henry Ford: Whether you think you can, or you think you can't, you're right.",
    "Henry Ford: Failure is simply the opportunity to begin again more intelligently.",
    "Henry Ford: Obstacles are those frightful things you see when you take your eyes off your goal.",
    "John D. Rockefeller: Don't be afraid to give up the good to go for the great.",
    "John D. Rockefeller: If you want to succeed, strike out on new paths.",
    "Thomas Edison: I have not failed. I've just found ways that won't work.",
    "Thomas Edison: Genius is one percent inspiration and ninety-nine percent perspiration.",
    "Thomas Edison: There is no substitute for hard work.",
    "Ralph Waldo Emerson: Do not go where the path may lead, go instead where there is no path.",
    "Ralph Waldo Emerson: The only person you are destined to become is the person you decide to be.",
    "Henry David Thoreau: Go confidently in the direction of your dreams.",
    "George Patton: Accept the challenges so that you can feel the exhilaration of victory.",
    "Albert Einstein: In the middle of difficulty lies opportunity.",
    "Albert Einstein: Life is like riding a bicycle. To keep your balance you must keep moving.",
    "Michelangelo: If people knew how hard I worked to gain my mastery, it would not seem so wonderful.",
    "Vincent van Gogh: Great things are done by a series of small things brought together.",
    "Beethoven: To play without passion is inexcusable.",
    "George Washington: It is better to offer no excuse than a bad one.",
    "Voltaire: Judge a man by his questions rather than by his answers.",
    "Plutarch: What we achieve inwardly will change outer reality.",
    "Mark Twain: Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
    "Mark Twain: Keep away from people who try to belittle your ambitions.",
    "Mark Twain: The greatest risk is not taking one.",
    "Mark Twain: To succeed in life, you need two things: ignorance and confidence.",
    "Mark Twain: The secret of getting ahead is getting started.",
    "Horace: Begin, be bold, and venture to be wise.",
    "Virgil: They can conquer who believe they can.",
    "Virgil: Fortune favors the bold.",
    "Ovid: Take rest; a field that has rested gives a bountiful crop.",
    "Ovid: Dripping water hollows out stone, not through force but through persistence.",
    "Demosthenes: Small opportunities are often the beginning of great enterprises.",
    "Pericles: What you leave behind is not what is engraved in stone monuments.",
    "Pliny the Elder: Fortune favors the brave.",
    "Tacitus: The desire for safety stands against every great and noble enterprise.",
    "Francis Bacon: A wise man will make more opportunities than he finds.",
    "Goethe: Knowing is not enough; we must apply.",
    "Schopenhauer: Talent hits a target no one else can hit; genius hits a target no one else can see.",
    "Friedrich Nietzsche: What does not kill me makes me stronger.",
    "William James: Act as if what you do makes a difference. It does.",
    "George Bernard Shaw: Life isn't about finding yourself. Life is about creating yourself.",
    "George Bernard Shaw: Progress is impossible without change.",
    "Helen Keller: Optimism is the faith that leads to achievement.",
    "Booker T. Washington: If you want to lift yourself up, lift up someone else.",
    "Florence Nightingale: I attribute my success to this: I never gave or took any excuse.",
    "Carl Jung: I am not what happened to me, I am what I choose to become.",
    "Henry Ward Beecher: Hold yourself responsible for a higher standard than anybody else expects.",
    "John Ruskin: Quality is never an accident; it is always the result of intelligent effort.",
    "Thomas Carlyle: Go as far as you can see; when you get there, you'll be able to see further.",
    "Samuel Smiles: He who never made a mistake never made a discovery.",
    "Frederick Douglass: If there is no struggle, there is no progress.",
    "Harriet Tubman: Every great dream begins with a dreamer.",
    "Henry Wadsworth Longfellow: The heights by great men reached were not attained by sudden flight.",
    "George Eliot: It is never too late to be what you might have been.",
    "Emily Dickinson: Forever is composed of nows.",
    "Miyamoto Musashi: You must understand that there is more than one path to the top of the mountain.",
    "Miyamoto Musashi: Today is victory over yourself of yesterday.",
    "Miyamoto Musashi: Think lightly of yourself and deeply of the world.",
    "Xunzi: Learning must never stop.",
    "Lao Tzu: Mastering others is strength; mastering yourself is true power.",
    "Lao Tzu: Nature does not hurry, yet everything is accomplished."
  ],
  commercialsHeaders: [
    "A brief commercial intermission for your boss journey",
    "Commercials selected by the Board of Dramatic Pauses",
    "Boss Commercials: now with extra unnecessary seriousness",
    "A short break for very important business ads",
    "Commercial diplomacy is now in session",
    "This ad break was approved by middle management",
    "A tasteful interruption enters the room",
    "Corporate destiny requested a quick commercial",
    "Please remain boss-like during this ad moment",
    "Even legends need a sponsored pause",
    "This interruption smells faintly of success",
    "Please clap politely for the upcoming advertisement",
    "Boss energy paused for strategic commercials",
    "Today's interruption arrives in a sharp suit",
    "Commercial time. Try to look interested",
    "A sponsored plot twist is loading",
    "Please welcome this highly motivated advertisement",
    "This commercial insists it has networking potential",
    "The ad team brought slides and confidence",
    "A brief detour into capitalism begins now",
    "An advertisement is clearing its throat dramatically",
    "This ad break believes in your potential",
    "A sponsored moment of destiny is unfolding",
    "Please stand by for professionally delivered persuasion",
    "This interruption was focus-grouped for maximum bossness",
    "A brief ad break, served with confidence",
    "The sponsors would like a tiny spotlight",
    "Corporate theater presents: one commercial",
    "This commercial arrived with PowerPoint energy",
    "The ad wishes to synergize with your evening",
    "The advertisement department requests your majestic patience",
    "A brief sponsored ceremony is underway",
    "The commercial insists this is a leadership opportunity",
    "This ad break comes with executive energy",
    "Corporate winds have summoned a commercial",
    "A refined pause for premium persuasion",
    "This advertisement has a confident handshake",
    "A moment of sponsored clarity arrives",
    "The board has approved this brief interruption",
    "A commercial approaches with quiet authority",
    "This advertisement believes in synergy",
    "Corporate alignment requires a short ad",
    "This commercial has prepared talking points",
    "A brief executive pause is now in effect",
    "The sponsors bring a message of opportunity",
    "A commercial with strong leadership qualities appears",
    "This commercial arrived wearing expensive loafers",
    "A sponsored interruption is practicing its pitch",
    "This ad break brought jargon and a laser pointer",
    "The commercial would like five minutes and trust",
    "A branded thought leader has entered the building",
    "This advertisement says circle back a lot",
    "The sponsors are smiling with deck intensity",
    "A commercial just CC'd the entire universe"
  ]
};

function pickNonRepeating(items, lastItem) {
  if (!Array.isArray(items) || items.length === 0) return "";
  if (items.length === 1) return items[0];

  let next = items[Math.floor(Math.random() * items.length)];
  for (let index = 0; index < 6; index += 1) {
    if (next !== lastItem) return next;
    next = items[Math.floor(Math.random() * items.length)];
  }

  return items.find((item) => item !== lastItem) || next;
}

window.BOSS_CONTENT = BOSS_CONTENT;
window.pickNonRepeating = pickNonRepeating;
